// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PARK.APP.FIRST.Areas.SystemManage.Models.System;

namespace PARK.APP.FIRST.Migrations.SystemDb
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PARK.APP.FIRST.Areas.SystemManage.Models.System.TcommonCode", b =>
                {
                    b.Property<string>("CodeType")
                        .HasMaxLength(32);

                    b.Property<string>("CodeId")
                        .HasMaxLength(32);

                    b.Property<string>("CodeComment")
                        .HasMaxLength(128);

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("CodeTypeName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int?>("CodeVal");

                    b.Property<DateTime?>("CreateDt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreateUserId")
                        .HasMaxLength(16);

                    b.Property<int?>("SortOrder");

                    b.Property<string>("UseYn")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("CodeType", "CodeId");

                    b.ToTable("TCommonCode");
                });
#pragma warning restore 612, 618
        }
    }
}
